server:
  port: 7001

env: 
  dev12
girl: 
  name: zhangsanjie
  age: 18


spring:
  application:
    name: orderservice
  



#  application:
#    name: order
#  cloud:
#    config:
#      discovery:
#        enabled: true
#        service-id: CONFIG
#      profile: test
#自定义轮询规则
#PRODUCTSERVICE:
 # ribbon:
  #  NFLoadBalancerClassName: com.netflix.loadbalancer.RandomRule
